stereo_matcher:
  blur_kernel : [3, 3]
  min_disp : 0
  max_disp : 256 # 64 or 128 or 256
  p1 : 10 # 8*9*7
  p2 : 120 # 32*9*7
  unique_ratio : 0
  mode : 3 # cv::StereoSGBM::MODE_HH : 1
post_filter:
  filter_size : 5
  refine_iter : 3
  edge_thresh : 0.1
  disc_thresh : 0.2
  sigma_range : 1.1
